name: better_auth_flutter_example
description: "Demo app for Better Auth Flutter SDK"

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  better_auth_flutter:
    path: ../
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  google_sign_in: 7.0.0
  flutter_web_auth_2: ^4.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
